#!/usr/bin/env bash

exec &> >(tee -a "/private/tmp/wakeup.log")

# Remove auth subkey, allows for dup/backup yubikey
sh ~/bin/clear_keygrip.sh

echo "before" && ps -ef |grep gpg-agent

pkill -9 gpg-agent
/usr/local/MacGPG2/bin/gpgconf --launch gpg-agent

echo "after" && ps -ef |grep gpg-agent

exit $?
