# If you come from bash you might have to change your $PATH.
# export TERM="xterm-256color"
export LC_ALL="en_US.UTF-8"
export EDITOR="vim"
export _Z_CMD=","
export GOPATH=$HOME/go
export NPM_PACKAGES=$HOME/.npm-packages

export PATH=$PATH:~/.local/bin:/usr/local/sbin:$NPM_PACKAGES/bin

{%@@ if v_os_type == 'Darwin' @@%}
# https://github.com/robbyrussell/oh-my-zsh/issues/6835#issuecomment-390216875
ZSH_DISABLE_COMPFIX=true
{%@@ endif @@%}

source ~/.alias

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
# can possibly slow down terminal
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status context dir newline virtualenv vcs)

{%@@ if v_os_type == 'Darwin' @@%}
# will not fight to get this on my home machine....
# powerlevel9k options
DEFAULT_FOREGROUND=154 DEFAULT_BACKGROUND=008
# # DEFAULT_SEP_FOREGROUND=023
# DEFAULT_SEGMENT_SEP_LEFT="\uE0B4 "
DEFAULT_SEGMENT_SEP_RIGHT="\uE0C7"
# DEFAULT_COLOR=$DEFAULT_FOREGROUND
#
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status context dir newline virtualenv vcs)
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir newline virtualenv vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode background_jobs status time)
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=006
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="$DEFAULT_FOREGROUND"
# POWERLEVEL9K_DIR_HOME_FOREGROUND="$DEFAULT_FOREGROUND"
# POWERLEVEL9K_DIR_HOME_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="$DEFAULT_FOREGROUND"
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_TIME_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_TIME_FOREGROUND=006
POWERLEVEL9K_STATUS_OK_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
# POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="$DEFAULT_SEGMENT_SEP_LEFT"
# POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
# # POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_SEP_FOREGROUND - 2 ))}|%f"
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="$DEFAULT_SEGMENT_SEP_RIGHT"
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""
# # POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_SEP_FOREGROUND - 2 ))}|%f"
# POWERLEVEL9K_VCS_CLEAN_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_VCS_CLEAN_FOREGROUND=blue
# POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=red
# POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="$DEFAULT_BACKGROUND"
# POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=yellow
# POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND=magenta
{%@@ endif @@%}

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(z git zsh-autosuggestions vault docker gpg-agent)

source $ZSH/oh-my-zsh.sh
# source ~/tmuxinator.zsh

hash kubectl 2>/dev/null && source <(kubectl completion zsh)
hash kops 2>/dev/null && source <(kops completion zsh)
hash aws 2>/dev/null && complete -C '/usr/bin/aws_completer' aws
hash jx 2>/dev/null && source <(jx completion zsh)


# source ~/.ssh/myrc

# zsh stuff
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '\e.' insert-last-word # Do not set KEYTIMEOUT too low, or it will not work!
bindkey -M vicmd v edit-command-line

export KEYTIMEOUT=20

setopt hist_ignore_all_dups
# run fzf install for that to be populated.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

{%@@ if v_os_type == 'Darwin' @@%}
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export SSH_AUTH_SOCKET=$HOME/.gnupg/S.gpg-agent.ssh
echo "SSH_AUTH_SOCK is set to $(readlink $SSH_AUTH_SOCK)"
gcloud_path="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
[[ -f $gcloud_path ]] && source $gcloud_path
gcloud_completion="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
[[ -f $gcloud_completion ]] && source $gcloud_completion
{%@@ else @@%}
xset -b
source /home/fblaise/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /home/fblaise/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /usr/bin/virtualenvwrapper

echo "SSH_AUTH_SOCK is set to $(echo $SSH_AUTH_SOCK)"
{%@@ endif @@%}

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=243'
echo UPDATESTARTUPTTY | gpg-connect-agent >/dev/null 

# fpath=( ~/.zsh_functions "${fpath[@]}" )
# autoload -Uz list-vault-keys
