actions:
  vundle: vim +PluginInstall +qall
trans:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
    trans:
      - gpg
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_i3status.conf:
    dst: ~/.i3status.conf
    src: i3status.conf
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    actions:
      - vundle
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  gimli:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_zshrc
    - f_xmodmap
    - f_tmux.conf
    - f_config
    - f_xresources
    - f_i3status.conf
    - f_alias
