actions:
  vundle: vim +PluginInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: true
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
  f_compton.conf:
    dst: ~/.compton.conf
    src: compton.conf
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_config_powerline_colorschemes_tmux_default.json:
    dst: ~/.config/powerline/colorschemes/tmux/default.json
    src: config/powerline/colorschemes/tmux/default.json
  f_config_powerline_themes_tmux_default.json:
    dst: ~/.config/powerline/themes/tmux/default.json
    src: config/powerline/themes/tmux/default.json
  f_config_powerline_themes_vim_default.json:
    dst: ~/.config/powerline/themes/vim/default.json
    src: config/powerline/themes/vim/default.json
  f_gtk.css:
    dst: ~/.config/gtk-3.0/gtk.css
    src: config/gtk-3.0/gtk.css
  f_homebrew.gpg.gpg-agent.plist:
    dst: ~/Library/LaunchAgents/homebrew.gpg.gpg-agent.plist
    src: Library/LaunchAgents/homebrew.gpg.gpg-agent.plist
  f_i3status.conf:
    dst: ~/.i3status.conf
    src: i3status.conf
  f_karabiner.json:
    dst: ~/.config/karabiner/karabiner.json
    src: config/karabiner/karabiner.json
  f_link-ssh-auth-sock.plist:
    dst: ~/Library/LaunchAgents/link-ssh-auth-sock.plist
    src: Library/LaunchAgents/link-ssh-auth-sock.plist
  f_n_clear_keygrip.sh:
    dst: ~/bin/clear_keygrip.sh
    src: bin/clear_keygrip.sh
  f_rvmrc:
    dst: ~/.rvmrc
    src: rvmrc
  f_sleep:
    dst: ~/.sleep
    src: sleep
  f_tmux-macos.conf:
    dst: ~/.tmux-macos.conf
    src: tmux-macos.conf
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    actions:
    - vundle
    dst: ~/.vimrc
    src: vimrc
  f_vimrc-osx-defaults:
    dst: ~/.vimrc-osx-defaults
    src: vimrc-osx-defaults
  f_vscode_user_settings_linux.json:
    dst: ~/.config/Code/User/settings.json
    src: Library/Application Support/Code/User/settings.json
  f_vscode_user_settings_mac.json:
    dst: ~/Library/Application Support/Code/User/settings.json
    src: Library/Application Support/Code/User/settings.json
  f_wakeup:
    dst: ~/.wakeup
    src: wakeup
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xrandr.sh:
    dst: ~/.i3/scripts/xrandr.sh
    src: i3/scripts/xrandr.sh
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  gimli:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_zshrc
    - f_xmodmap
    - f_tmux.conf
    - f_config
    - f_xresources
    - f_i3status.conf
    - f_alias
    - f_gtk.css
    - f_compton.conf
    - f_xrandr.sh
    - f_config_powerline_colorschemes_tmux_default.json
    - f_config_powerline_themes_tmux_default.json
    - f_config_powerline_themes_vim_default.json
    - f_vscode_user_settings_linux.json
    - f_rvmrc
  mbp2012:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_tmux.conf
    - f_alias
    - f_tmux-macos.conf
    - f_karabiner.json
    - f_wakeup
    - f_sleep
    - f_homebrew.gpg.gpg-agent.plist
    - f_link-ssh-auth-sock.plist
    - f_vimrc-osx-defaults
    - f_vscode_user_settings_mac.json
    - f_config_powerline_colorschemes_tmux_default.json
    - f_config_powerline_themes_tmux_default.json
    - f_config_powerline_themes_vim_default.json
    - f_n_clear_keygrip.sh
    - f_rvmrc
  tower:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_zshrc
    - f_xmodmap
    - f_tmux.conf
    - f_config
    - f_xresources
    - f_i3status.conf
    - f_alias
    - f_gtk.css
    - f_compton.conf
    - f_xrandr.sh
    - f_tmux.conf
    - f_config_powerline_colorschemes_tmux_default.json
    - f_config_powerline_themes_tmux_default.json
    - f_vscode_user_settings_linux.json
    - f_config_powerline_themes_vim_default.json
    - f_rvmrc
trans:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
