actions:
  vundle: vim +PluginInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_70-u2f.rules:
    dst: /etc/udev/rules.d/70-u2f.rules
    src: etc/udev/rules.d/70-u2f.rules
  f_alias:
    dst: ~/.alias
    src: alias
    trans:
    - gpg
  f_compton.conf:
    dst: ~/.compton.conf
    src: compton.conf
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_gtk.css:
    dst: ~/.config/gtk-3.0/gtk.css
    src: config/gtk-3.0/gtk.css
  f_i3status.conf:
    dst: ~/.i3status.conf
    src: i3status.conf
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    actions:
    - vundle
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xrandr.sh:
    dst: ~/.i3/scripts/xrandr.sh
    src: i3/scripts/xrandr.sh
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  gimli:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_zshrc
    - f_xmodmap
    - f_tmux.conf
    - f_config
    - f_xresources
    - f_i3status.conf
    - f_alias
    - f_gtk.css
    - f_70-u2f.rules
    - f_compton.conf
    - f_xrandr.sh
trans:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
